### ISSUE TITLE
Feature req: insult & compliment mgmt

### ISSUE THREAD

**Issue by misse** [IcEBnd/pyirkbot#17]
Feature: The ability to list and remove compliments / insults via f.e. a privmessage to the bot.

Reason: Some of the insults are compliments and or suck.

**Comment by IcEBnd** [comment]
Förslag:
.insultmgmt 
Available commands are....

.insultmgmt list [page]
.insultmgmt search "regexp" [page]
.insultmgmt list-hidden [page]
.insultmgmt search-hidden "regexp" [page]
Page [2/231]: 6. %s is adablabla 7. %s %s %s %s asdasd ...

.insultmgmt hide [insult-nr]
Marked 6 as hidden, "%s is adablabla"

.insultmgmt show [hidden-insult-nr]

**Comment by the-louie** [comment]
Make it so!
